### PR TITLE
Refact class components to function components and hooks

### LINKED ISSUE #66: Remove components using deprecated lifecycle
**Describe the bug**
componentWillReceiveProps and componentWillMount are being deprecated by react, we actually have some components and a dependency (Formik) which uses those lifecycles. We need to refactor those components and update the Formik version

### PR DESCRIPTION
**Pull request by lucasmedeiros**
Fix #66 

As the title says, this Pull Request adds functional components and hooks to all class components used in this project, and changes deprecated lifecycles for hooks like *useEffect*. 

**Important**: I removed all typings while refactoring, as I talked to @JoseRenan and @JRobsonJr.

### CODE REVIEW

File: musicritic/src/components/album/AlbumPage.js [hunk 1]
```diff
@@ -11,69 +10,50 @@ import AlbumPageContent from './content/AlbumPageContent';
...
+        <SomeComponent {...props} />
+    </section>
+);
+
+function AlbumPage(props) {
+    const [album, setAlbum] = useState({});
+    const [artistAlbums, setArtistsAlbum] = useState([]);
+    const [mainArtist, setMainArtist] = useState({});
+
+    useEffect(() => {
```
Comment (JoseRenan) [inline musicritic/src/components/album/AlbumPage.js]: Hey @lucasmedeiros, there is a custom hook that we use to handle promises, [`usePromise(promise, initialState, deps)`](https://github.com/calluswhatyouwant/musicritic/blob/master/musicritic/src/utils/hooks.js#L3), so instead of calling `getAlbum(id)` and `getArtistAlbums()` directly and set their respective states, you can declare:

```js
const [album, errorGetAlbum, loadingAlbum] = usePromise(getAlbum(id), {}, [id]);
```
It will automatically make all the necessary work to manage the album state and also refecth the album whenever the `id` changes

Comment (JoseRenan) [reply musicritic/src/components/album/AlbumPage.js]: There is an example on [SearchResultsPage.js](https://github.com/calluswhatyouwant/musicritic/blob/master/musicritic/src/components/search/SearchResultsPage.js)

File: musicritic/src/components/search/results/AlbumResults.js [hunk 2]
```diff
@@ -1,50 +1,31 @@
...
+            setAlbums(results);
+        },
+        [results]
+    );
+
+    const handleClick = album => {
+        history.push(`/album/${album.id}/`);
+    };
+
+    const listResults = albums.map(album => (
```
Comment (JoseRenan) [inline musicritic/src/components/search/results/AlbumResults.js]: I was wondering if we need a state for albums since we just render it directly, this way we could just remove the state and the list result would be:

```js
const listResults = results.map(album => ) ...
```

File: musicritic/src/components/search/results/PlaylistResults.js [hunk 3]
```diff
@@ -1,42 +1,27 @@
...
+    const [playlists, setPlaylists] = useState(results);
+
+    useEffect(
+        () => {
+            setPlaylists(results);
+        },
+        [results]
+    );
+
+    const listResults = playlists.map(playlist => (
```
Comment (JoseRenan) [inline musicritic/src/components/search/results/PlaylistResults.js]: I was wondering if we need a state for playlists since we just render it directly, this way we could just remove the state and the list result would be:

```js
const listResults = results.map(playlist => ) ...
```

File: musicritic/src/components/search/results/TrackResults.js [hunk 4]
```diff
@@ -1,50 +1,36 @@
...
+        history.push(`/track/${track.id}`);
     }
 
-    handleClick = (track: Track) => {
-        this.props.history.push(`/track/${track.id}`);
-    };
-
-    render() {
-        const listResults = this.state.tracks.map(track => (
+    const listResults =
```
Comment (JoseRenan) [inline musicritic/src/components/search/results/TrackResults.js]: Same issue about the state here

File: musicritic/src/components/search/results/PlaylistResults.js (hunk 3 above)
Comment (JoseRenan) [reply musicritic/src/components/search/results/PlaylistResults.js]: Also, since it repeats four times, maybe we can reuse this component changing only the card we have :thinking: using it like:

```jsx
<Results results={results} card={<PlaylistCard />} />
```

File: musicritic/src/components/track/TrackPage.js [hunk 5]
```diff
@@ -1,45 +1,23 @@
...
-    constructor(props: Props) {
-        super(props);
-        this.state = {
-            trackId: this.props.match.params.id,
-            track: {},
-        };
-    }
+    useEffect(() => {
+        async function getTrackFromAPI() {
+            const trackResponse = await getTrack(props.match.params.id);
```
Comment (JoseRenan) [inline musicritic/src/components/track/TrackPage.js]: change `props.match.params.id` to `useParams` from react router

**Review by JoseRenan — DISMISSED** [review]
Hey @lucasmedeiros, thank you for the contribution :heart: I've requested some changes just to align with our current refactor. And also, since it's a refactor, I've put other minor change that is not related to hooks, but is optional to this PR, because it was this way before your PR, so it's our fault

File: musicritic/src/components/search/results/PlaylistResults.js (hunk 3 above)
Comment (lucasmedeiros) [reply musicritic/src/components/search/results/PlaylistResults.js]: I think that this refactor may be done on other issue/pull request, because if I change it here, it will not be following the purpose of this PR and issue

File: musicritic/src/components/login/Auth.js [hunk 6]
```diff
@@ -1,21 +1,15 @@
...
-};
-
-class Auth extends Component<Props> {
-    componentDidMount() {
-        localStorage.setItem('token', this.props.match.params.token);
-        localStorage.setItem('refresh', this.props.match.params.refresh);
-    }
+const Auth = props => {
+    useEffect(() => {
+        localStorage.setItem('token', props.match.params.token);
```
[the remark this answers is not in the document]
Comment (lucasmedeiros) [reply musicritic/src/components/login/Auth.js]: done

File: musicritic/src/components/album/AlbumPage.js [hunk 7]
```diff
@@ -11,69 +10,50 @@ import AlbumPageContent from './content/AlbumPageContent';
...
-                {wrapComponent(AlbumSummary, {
-                    album,
-                    artistAlbums,
-                    mainArtist,
-                })}
-                {wrapComponent(AlbumPageContent, { album })}
-            </div>
-        );
-    }
+        updateAlbumData(props.match.params.id);
```
[the remark this answers is not in the document]
Comment (lucasmedeiros) [reply musicritic/src/components/album/AlbumPage.js]: done

File: musicritic/src/components/track/TrackPage.js (hunk 5 above)
Comment (lucasmedeiros) [reply musicritic/src/components/track/TrackPage.js]: done

File: musicritic/src/components/album/AlbumPage.js (hunk 1 above)
Comment (lucasmedeiros) [reply musicritic/src/components/album/AlbumPage.js]: done

**Comment by lucasmedeiros** [comment]
@JoseRenan I made some changes you've requested and commented on others, please take a look when you can :smile:

**Review by JRobsonJr — DISMISSED** [review]
Hey Lucas, thank you for your contribution and sorry for the huge delay in merging this! :sparkles:

**Review by JRobsonJr — APPROVED** [review]
